services:
    web:
        container_name: web
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:3000
        restart: always
        environment:
            NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
            NEXT_PUBLIC_API_ENDPOINT: ${NEXT_PUBLIC_API_ENDPOINT}
            NEXT_PUBLIC_API_HOST: ${NEXT_PUBLIC_API_HOST}

