api:
  insecure: false

accessLog: {}

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: http
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      httpChallenge:
        entryPoint: web
      email: ${TRAEFIK_CERTIFICATE_EMAIL}
      storage: /letsencrypt/acme.json
      tlsChallenge: {}
